### ISSUE TITLE
Missing Article section

### ISSUE THREAD

**Issue by kststudio** [ZM202/hike-project#13]
@bookcase201 Please add merge this section to the project

**Comment by ZM202** [comment]
There is an article section that was merged with nav & gear sections on Sat. I think maybe it didn't get push it correctly. Will check. Thanks.

**Comment by kststudio** [comment]
@ZM202 Currently in index.html on the master branch, there is no code for the article so its currently missing. You will need to create a new branch for your article section, push to your repo, and create a pull request to merge into the master branch on this projects repo.

**Comment by ZM202** [comment]
@kststudio hopefully it is updated now.. thanks.

**Comment by kststudio** [comment]
@ZM202 I can see it now! It looks good!
